spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://desafioapi.postgres.database.azure.com:5432/sprint_7
    username: apiuser
    password: Ju2111200
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: suportecodewave@gmail.com
    password: mhlrnhukkrfcsoxp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true