spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/sprint_7
    username: postgres
    password: jucaprevost21112004
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true