spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio
    username: postgres
    password: 904090ef
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: suportecodewave@gmail.com
    password: mhlrnhukkrfcsoxp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true