spring:
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://localhost:5432/Desafio_JPA
    username: postgres
    password: Spiderman51
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true